package rules.tradeManagement;

import org.trading.model.*;
import org.trading.event.*;

dialect  "mvel"

rule "Account equity first insert"
    when
      AccountEquityEvent($account: account, $equity: equity) from entry-point "ACCOUNT_EQUITY"
      not AccountEquity()
    then
      insert(new AccountEquity($account, $equity));
      System.out.println("Account equity first insert " + $equity + " for " + $account);
end

// Dont want to trigger any rules when I update account
rule "Account equity change"
    when
      AccountEquityEvent($account: account, $equity: equity) from entry-point "ACCOUNT_EQUITY"
      $a: AccountEquity(account == $account)
    then
      $a.setEquity($equity);
      System.out.println("Account equity updated with level " + $equity + " for " + $account);
end
