package rules.tradeManagement;

import org.trading.model.*;
import org.trading.event.*

dialect  "mvel"

rule "Update ATR for Market"
    when
      AtrEvent($e: epic, $l: level) from entry-point "ATR"
      $sd: SystemData(epic == $e)
    then
      modify($sd){setCurrentAtr($l)}
end

// TODO when ATR for market change and there is an order for that market, risk adjust it
// I should subscribe to only changes on ATR field in MarketInfo for this, chekc book how to do that