package rules.tradeManagement;

import org.trading.model.*;
import org.trading.event.*;
import org.trading.ChannelIds
import org.trading.command.FetchOpeningRangeCommand;

dialect  "mvel"

rule "On each bid event trigger"
    when
      $b: Bid($e: epic) from entry-point "BID"
    then
      channels[ChannelIds.OPEN_WORKING_ORDER].send(new FetchOpeningRangeCommand($e));
end

query "Get Last 5min bids"
  $b: Bid() over window:time(5m) from entry-point "BID"
end