package rules.tradeManagement;

import org.trading.model.*;
import org.trading.event.*;
import org.trading.ChannelIds;

dialect  "mvel"

rule "Cleanup opening range when market close"
    when
      MarketClose($e: epic) from entry-point "MARKET_CLOSE"
      $or: OpeningRange(epic == $e)
    then
      System.out.println("Cleanup market close at close for " + $e);
      delete($or);
end

rule "Cleanup atr when market close"
    when
      MarketClose($e: epic) from entry-point "MARKET_CLOSE"
      $atr: Atr(epic == $e)
    then
      System.out.println("Cleanup ATR at close for " + $e);
      delete($atr);
end
