package rules.tradeManagement;

import org.trading.model.*;
import org.trading.event.*;
import org.trading.*;
import org.trading.ChannelIds
import org.trading.command.CreateWorkingOrderCommand
import org.trading.command.UpdateWorkingOrderCommand

dialect  "mvel"

rule "Update latest price for market"
    when
      MidPriceEvent($e: epic, $l: level, $sp: getSpread()) from entry-point "MID_PRICE"
      $sd: SystemData(epic == $e)
      AccountEquity()
    then
      modify($sd){setCurrentMidPrice($l), setCurrentSpread($sp)}
end
