package rules.tradeManagement;

import org.trading.model.*;
import org.trading.event.*
import org.trading.ChannelIds
import org.trading.command.DeleteWorkingOrderCommand;
import java.util.List
import org.trading.command.TradeResultCommand;

dialect  "mvel"

rule "Post trade result for all exited positions"
    when
      $p: Position(state == "EXIT")
    then
      channels[ChannelIds.TRADE_RESULT].send(new TradeResultCommand());
      delete($p);
end