package rules.tradeManagement;

import org.trading.model.*;
import org.trading.event.*;
import org.trading.ChannelIds;

dialect  "mvel"

rule "Instert system data"
    when
      $sd: SystemData() from entry-point "SYSTEM_DATA"
    then
      insert($sd)
      System.out.println("Insert system data");
end

rule "Instert system data is here"
    when
      not SystemData()
    then
      System.out.println("SYSTEM DATA IS HERE");
end

rule "On each ATR update for market"
    when
      SystemData($atr: currentAtr != null) @Watch(currentAtr)
    then
      System.out.println("ATR WATCH Change so trigger risk adjustment for " + $atr);
end

rule "NULL On each MidPrice update for market"
    when
      $sd: SystemData($epic: epic, $price: currentMidPrice == null) @watch(currentMidPrice)
    then
      System.out.println("NULL MidPrice WATCH Change " + $epic);
end

rule "HIGHER On each MidPrice update for market"
    when
      $sd: SystemData($epic: epic, $price: currentMidPrice > 13235.) @watch(currentMidPrice)
    then
      System.out.println("HIGHR MidPrice WATCH Change " + $epic);
end

rule "LOWER On each MidPrice update for market"
    when
      $sd: SystemData($epic: epic, $price: currentMidPrice < 13235.) @watch(currentMidPrice)
    then
      System.out.println("LOWER MidPrice WATCH Change " + $epic);
end
