ig:
  identifier: ${IG_DEMO_IDENTIFIER:}
  password: ${IG_DEMO_PASSWORD:}
  apiKey: ${IG_DEMO_APIKEY:}
  baseUrl: https://demo-api.ig.com/gateway/deal
market:
  epics:
    -
      epic: IX.D.DAX.IFMM.IP
      spread: 1.4,
      expiry: "-"
      currency: EUR
      minStop: 5
      maxStopMultiplier: 7
      lotSize: 1
      localOpenTime: "09:00"
      localCloseTime: "17:30"
      marketZone: EU
      nonTradingDays:
        - "2023-12-24"
      barsInOpeningRange: 1
    -
      epic: IX.D.NASDAQ.IFE.IP
      spread: 1.,
      expiry: "-"
      currency: EUR
      minStop: 4
      maxStopMultiplier: 8
      lotSize: 1
      localOpenTime: "09:00"
      localCloseTime: "17:30"
      marketZone: US
      nonTradingDays:
        - "2023-12-24"
      barsInOpeningRange: 5

logging:
  level:
    root: info

spring:
  mvc:
    hiddenmethod: #Check spring in practice book why this is needed
      filter:
        enabled: true